### ISSUE TITLE
home-manager

### ISSUE THREAD

**Issue by truxnell** [truxnell/nix-config#2]
Setup isolated (i.e. modules in its folder)

- [ ] GNOME 
- [ ] DCONF - https://github.com/gvolpe/dconf2nix
- [ ] vscodium
- [ ] prusaslicer
- [ ] firefox
- [ ] discord
- [ ] spotify
- [ ] syncthing
- [ ] export age key on destop systems for sops managment
- [ ] mail program (as below, using maddy relay?)

**Comment by truxnell** [comment]
# # TODO Email settings
  # programs.msmtp = {
  #   enable = true;
  #   accounts.default = {
  #     host = "maddy.home.tld";
  #     from = "${config.networking.hostName}@trux.dev";
  #   };
  #   defaults = {
  #     aliases = "/etc/aliases";
  #   };
  # };
