### ISSUE TITLE
NAS todo

### ISSUE THREAD

**Issue by truxnell** [truxnell/nix-config#216]
- [x] snapraid
- [x] mergerfs
- [ ] restic NAS backup to b2
- [ ] move drives to new case
- [ ] move plex
- [ ] immich
- [ ] investigate nix cache
- [ ] autoupdates

Alerts
- [ ] ZFS issue
- [ ] disks full
- [ ] CPU high
- [ ] RAM high
- [ ] SMART errors
- [ ] SNAPraid issues
- [ ]
